#![allow ( dead_code )]
#![allow ( mutable_transmutes )]
#![allow ( non_camel_case_types )]
#![allow ( non_snake_case )]
#![allow ( non_upper_case_globals )]
#![allow ( unused_mut )]
#![feature ( extern_types )]
#![feature ( i128_type )]
#![feature ( libc )]
#![feature ( offset_to )]
#![feature(start)]
pub mod rans_static;
